
AZURE_OPENAI_ENDPOINT = config('AZURE_OPENAI_ENDPOINT')
AZURE_OPENAI_REALTIME_DEPLOYMENT = config('AZURE_OPENAI_REALTIME_DEPLOYMENT')
AZURE_OPENAI_REALTIME_VOICE_CHOICE = config('AZURE_OPENAI_REALTIME_VOICE_CHOICE')
AZURE_OPENAI_API_KEY = config('AZURE_OPENAI_API_KEY')
AZURE_SEARCH_ENDPOINT = config('AZURE_SEARCH_ENDPOINT')
AZURE_SEARCH_INDEX = config('AZURE_SEARCH_INDEX')
AZURE_SEARCH_API_KEY = config('AZURE_SEARCH_API_KEY')