from decouple import config

AZURE_OPENAI_WS_ENDPOINT = config('AZURE_OPENAI_WS_ENDPOINT')
AZURE_OPENAI_WS_DEPLOYMENT = config('AZURE_OPENAI_WS_DEPLOYMENT')
AZURE_OPENAI_API_KEY = config('AZURE_OPENAI_API_KEY')
OPENAI_CHAT_MODEL = config('OPENAI_CHAT_MODEL')
AZURE_OPENAI_ENDPOINT = config('AZURE_OPENAI_ENDPOINT')
# AZURE_SEARCH_INDEX = config('AZURE_SEARCH_INDEX')
# AZURE_SEARCH_API_KEY = config('AZURE_SEARCH_API_KEY')